// src/components/layout/AppNavigation.vue
<template>
  <div class="mx-auto max-w-7xl overflow-x-auto px-4 pb-2">
    <div class="flex gap-1">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        class="nav-tab whitespace-nowrap"
        :class="active === tab.id
          ? (darkMode ? 'nav-tab-active-dark' : 'nav-tab-active')
          : (darkMode ? 'nav-tab-dark' : '')"
        @click="$emit('navigate', tab.id)"
      >{{ tab.icon }} {{ tab.label }}</button>
    </div>
  </div>
</template>

<script setup>
defineProps({
  tabs: { type: Array, default: () => [] },
  active: { type: String, default: '' },
  darkMode: { type: Boolean, default: false }
})

defineEmits(['navigate'])
</script>

<style scoped>
.nav-tab {
  border-radius: 8px; padding: 6px 14px; font-size: 12px; font-weight: 700;
  color: #64748b; transition: all 0.15s;
}
.nav-tab:hover { background: #f1f5f9; }
.nav-tab-active { background: #22c55e; color: white; }
.nav-tab-dark { color: #94a3b8; }
.nav-tab-dark:hover { background: #334155; }
.nav-tab-active-dark { background: #22c55e; color: white; }
</style>

// src/components/AppNavigation.tsx
interface Tab {
  id: string
  label: string
  icon?: string
}

interface Props {
  tabs: Tab[]
  activeTab: string
  onNavigate: (id: string) => void
}

export default function AppNavigation({ tabs, activeTab, onNavigate }: Props) {
  return (
    <nav className="border-b border-border/60 bg-card/50 px-4 py-3 backdrop-blur-sm" role="tablist">
      <div className="mx-auto flex w-full max-w-[1680px] flex-wrap gap-2">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => onNavigate(tab.id)}
            role="tab"
            aria-selected={activeTab === tab.id}
            aria-label={tab.label}
            className={`rounded-xl px-4 py-2.5 text-sm font-bold transition-all ${
              activeTab === tab.id
                ? 'bg-primary text-primary-foreground shadow-sm'
                : 'bg-background/70 text-muted-foreground hover:bg-muted hover:text-foreground'
            }`}
          >
            {tab.icon && <span className="mr-2" aria-hidden="true">{tab.icon}</span>}
            {tab.label}
          </button>
        ))}
      </div>
    </nav>
  )
}
